{"name": "test_image", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/Desktop/123.png'", "trace": "self = <test_calculator.TestCalc object at 0x7f8ed988ec70>\n\n    def test_image(self):\n>       allure.attach.file('/Users/x/Desktop/123.png',\n                           name='图片',attachment_type=allure.attachment_type.PNG)\n\ntest_calculator.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../venv/lib/python3.8/site-packages/allure_commons/_allure.py:167: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n../venv/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n../venv/lib/python3.8/site-packages/allure_pytest/listener.py:219: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n../venv/lib/python3.8/site-packages/allure_commons/reporter.py:113: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n../venv/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../venv/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n../venv/lib/python3.8/site-packages/allure_commons/logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py:432: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nsrc = '/Users/x/Desktop/123.png'\ndst = '/Users/x/PycharmProjects/LaGouDemo/testing/.result/5a823973-aefc-4822-86a1-0c657849431d-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\nE           FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/Desktop/123.png'\n\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py:261: FileNotFoundError"}, "attachments": [{"name": "图片", "source": "5a823973-aefc-4822-86a1-0c657849431d-attachment.png", "type": "image/png"}], "start": 1596963949509, "stop": 1596963949509, "uuid": "a048fced-9c65-4a2d-a4af-9ed938589d6a", "historyId": "d3e26562afa715e905d16a06596cca21", "testCaseId": "feab09ce0a3df35d51a3926ccbd4c980", "fullName": "test_calculator.TestCalc#test_image", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "xzhdeMacBook-Pro.local"}, {"name": "thread", "value": "29063-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}